---
title: "Reproducible documents"
author: "Kaja"
format: html
---


```{r setup}
#| message: FALSE
#| warning: false
library(tidyverse)
library(NHANES)
nhanes_small <- read_csv(here::here("data/nhanes_small.csv"))
```

```{r}
nhanes_small

```

## Table of results

```{r mean-age-bmi-table}
nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>% 
    knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.")





```

```{r mean-age-bmi-table}
nhanes_small %>%
  filter(!is.na(education)) %>%
  group_by(education, levels=c("8th Grade", "9 - 11th Grade", "High School", "Some College", "College Grad" )) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>% 
    knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.") 





```
